# prettier-ignore
services:
  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=eventor
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - dump-data:/var/lib/postgresql/data

volumes:
  dump-data:
