# prettier-ignore
services:
  api:
    container_name: eventor-api
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
    depends_on:
      - db
      
  db:
    container_name: eventor-db
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - dump-data:/var/lib/postgresql/data

volumes:
  dump-data:
